### ISSUE TITLE
ci using extism cli

### ISSUE THREAD

**Issue by nilslice** [extism/assemblyscript-pdk#2]
@zshipko, if you get a chance, can you take a look at the `ci` branch & the CI workflow in particular.. I can't seem to get the CLI installed in such a way that it uses the installed lib/.h and doesn't attempt to fetch git resources. 

See: https://github.com/extism/assemblyscript-pdk/runs/8218063319?check_suite_focus=true

**Comment by zshipko** [comment]
I pushed a commit to `extism/cli` to use the http remote and pushed a commit to `ci` to install cffi and now ci is passing!

**Comment by nilslice** [comment]
Awesome! I tried to switch to http remote in the CLI earlier but when I used it locally GitHub wanted to auth me with username and password which is no longer supported... do you happen to hit the same issue when you use it locally now?

**Comment by nilslice** [comment]
(This was when attempting to `extism install git`)

**Comment by zshipko** [comment]
I think it's because there was a typo in the url but `extism install git` is working for me now

**Comment by nilslice** [comment]
Haha wow I didn't notice that 🤦 - good catch!
